# Generated by Django 5.0.3 on 2024-09-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="guardian_contact",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="guardian_name",
        ),
    ]
