# Generated by Django 5.0.3 on 2024-10-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogress",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
